### ISSUE TITLE
Interfaces aren't compatable 

### ISSUE THREAD

**Issue by kilahm** [fredemmott/http-message-hhi#2]
There appears to be an issue with defining scalar types in hhi files for interfaces defined in php files.  This is relevant in many places in this library, but the example below is a minimal example.

```
<?hh // strict
// Foo.hhi
interface Foo {
    public function bar(int $herp):void;
}
```

```
<?php
// Foo.php
interface Foo {
    public function bar($herp);
}
```

```
<?hh // strict
// HackImplementation.php

require './Foo.php';

class HackImplementation implements Foo {
    public function bar(int $herp): void {}
}
```

The type checker will not complain (rightly so), but attempting to execute `hhvm HackImplementation.php` results in

```
Fatal error: Declaration of HackImplementation::bar() must be compatible with that of Foo::bar() in HackImplementation.php on line 6
```

The runtime error can be removed by making making the interface defined in the hhi file have nullable scalar types.  I could easily create a PR to make all scalar parameters and return types nullable... would you be interested in that?

**Comment by fredemmott** [comment]
This might need a split; as-is, the types are correct for users of PSR7, but you're right, they can't be used to implement PSR7. I believe this is best as:
- It can't be done without weakening the constraints further, which is bad for more projects
- A pure Hack solution to the problem shouldn't implement PSR-7 for the reasons in the Notes section of the README here; something similar but actually type-safe should be agreed on by the community. The HHVM General group on Facebook is probably a good place to start. IMO PSR-7 is fundamentally not suitable for either Hack or for PHP7 scalar types

**Comment by fredemmott** [comment]
closing, this is not fixable.
